### PR TITLE
chore: update README

### PR DESCRIPTION
**Pull request by danielamiao**
Added some instructions to view and specify region upon sign up - tried to keep it short / frictionless but open to feedback!

@poppoerika would appreciate if you can push up the Japanese translated version to reflect these changes.

### CODE REVIEW

**Review by rlinehan — APPROVED** [review]
I think this looks good to me!

We were talking about also adding a note about old versions getting errors on `account signup` and users should upgrade. Should we do that now or hold off for another PR?

**Comment by danielamiao** [comment]
@rlinehan yes good point we should probably just add it now I'll push up an edit

**Comment by poppoerika** [comment]
@danielamiao / @rlinehan - I'd like to add Japanese translation for this updates to this branch, so could you hold off merging it?

**Comment by danielamiao** [comment]
@poppoerika Thanks! I just pushed up an additional change to add the message Ruth suggested.

**Review by rlinehan — DISMISSED** [review]
English language changes look good to me!

**Review by poppoerika — APPROVED** [review]

**Comment by poppoerika** [comment]
@danielamiao JP version is updated.

**Pull request merged**
