### PR TITLE
feat: create default cache when configuring profile

### PR DESCRIPTION
**Pull request by bruuuuuuuce**
Screen Shot 2022-03-01 at 12 07 11 PM

Do we want to show them that we are creating a cache from them? Or should we hide the logging

### CODE REVIEW

**Comment by bruuuuuuuce** [comment]
for some reason I am not able to transfer this issue over https://github.com/momentohq/dev-eco-issue-tracker/issues/38 to this repo

**Comment by mjindalmotiv8** [comment]
I think instead of `create cache called` - maybe we can change it to `creating cache`

**Comment by mjindalmotiv8** [comment]
What is the experience when create cache fails?

**Comment by danielamiao** [comment]
@bruuuuuuuce probably cuz it's a private => public repo. What happens if the cache name already exists?

**Comment by bruuuuuuuce** [comment]
> @bruuuuuuuce probably cuz it's a private => public repo. What happens if the cache name already exists?

If the api call fails you will just see this
Screen Shot 2022-03-01 at 12 15 46 PM

**Comment by danielamiao** [comment]
@bruuuuuuuce looks like the same screenshot?

**Comment by bruuuuuuuce** [comment]
> @bruuuuuuuce looks like the same screenshot?

So if the cache creates successfully you will see

```
create cache called
created cache <name>
```

if it fails you will just see
```
create cache called
```

**Comment by bruuuuuuuce** [comment]
I honestly think it might be better to just not even show anything, but this was the simpler change so i put this up first.

**Comment by danielamiao** [comment]
| I honestly think it might be better to just not even show anything, but this was the simpler change so i put this up first.

I think it's definitely better to show nothing if the call fails - user will run into the error on the next get/set command, which is what happens now. Currently, the message is confusing to show - it makes me think it created it for me successfully

**Comment by eaddingtonwhite** [comment]
I would just show nothing at all then if were not going to show failures. we should not show that we are doing this or if it succeeds.

Maybe in CLI then on get and set we can handle Cache not found error and prompt them with command to create cache or even try to do it lazily for them if we detect first call fails.

**Comment by danielamiao** [comment]
> Maybe in CLI then on get and set we can handle Cache not found error and prompt them with command to create cache 

I like this, but we can do this in a separate PR as an improvement to handle cases where creates fails during `momento configure`

**Comment by bruuuuuuuce** [comment]
Screen Shot 2022-03-08 at 9 38 55 AM

**Comment by danielamiao** [comment]
LGTM, added @poppoerika to review as well since this might conflict with her other PR after getting merged.

**Review by poppoerika — COMMENTED** [review]
Looks good to me as well. 
Updates to my pr won't be too much!

**Comment by danielamiao** [comment]
@bruuuuuuuce one more request:
- When calling create cache, change message to `creating cache...`, as @mjindalmotiv8 suggested above.
- After the call returns, either print `default cache successfully created` or `default cache already exists` depending on if the response was OK or not

**Pull request merged**
